name: Deploy Flask Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/AWSPortfolio

            git fetch origin
            git reset --hard origin/main
            git clean -fd

            source venv/bin/activate

            pip install -r requirements.txt

            sudo systemctl restart pankaj-python-app

            sudo systemctl status pankaj-python-app --no-pager